### ISSUE TITLE
react组件编写过程中的问题

### ISSUE THREAD

**Issue by AmyShieh** [lewis617/react-redux-book#12]
你好，我在编写react组件时，遇到一个问题
我是通过 npm create-react-app XXX来创建的项目
但是在做的过程中，我发现系统自动生成的文件路径以及默认的文件内容与你书中的不一致，我不知道该保留哪一个。
我现在在index.html中引入打包好的main.js（其实这个路径也和你说的不一样，我的main.js是在build/static/...下的）会报错。

我又换了另一种方式就是
直接npm init 来生成package.json文件 ，但这个文件中的script中缺少很多东西- -  运行都没办法运行

想请问一下，你在最开始是怎么创建项目的呢？（因为是初学者，我自己百度也没找到原因，问的问题可能比较浅显，实在不好意思。打扰了）

**Comment by lewis617** [comment]
1，书中的代码结构只是用来参考，大部分书中的代码比工作中用到的要复杂，你只用参考一部分即可。

2，最开始是如何创建项目？

- create-react-app 是很好的选择，不过要保证你的网络没有被墙。
- 如果能根据书中的课程一步步来做并理解的，你是完全可以自己搭建项目的。
- 最后，选择一些开源的经常更新的react的starter项目也可以。

希望能帮到你。

**Comment by AmyShieh** [comment]
好的。谢谢啦。我之前其实就是很好奇package.json里的东西是怎么来的，昨天也查了很多资料，大概了解啦~~~
