### ISSUE TITLE
19-1运行报错

### ISSUE THREAD

**Issue by shesio** [lewis617/react-redux-book#14]
一直打印以下日志：
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)

**Comment by shesio** [comment]
必须 手动添加  webpack-assets.json 文件

**Comment by lewis617** [comment]
这个轮子造的很差，可以看下之前的 issue，大部分都因为使用了 cnpm，不要用 cnpm， 用 npm 和 yarn，慢的话就配置淘宝源。

**Comment by trust2065** [comment]
我用yarn 安裝dependency後`yarn start`
cmd 也是一直吐 
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
...

手動新增webpack-assets.json檔案與內容後可以執行

------------
然後我複製Counter.png, 再試一次`yarn start`, 實驗看看是不是只有第一次無法執行
```
ew WebpackIsomorphicTools(config).development().server(__dirname, function() {
  console.log(require("./Counter.png"));
  console.log(require("./Counter2.png"));
});
```
```
λ yarn start
yarn run v1.12.3
$ node index.js
/dist/Counter.png
[webpack-isomorphic-tools] [error] asset not found: ./Counter2.png
undefined
Done in 1.04s.
```

還是無法正確的執行工具

**Comment by lewis617** [comment]
@trust2065 参考一下 webpack-isomorphic-tools 的最新用法
