### ISSUE TITLE
第三章 在浏览器中运行总是报错

### ISSUE THREAD

**Issue by 812913** [lewis617/react-redux-book#16]
![03_issue](https://user-images.githubusercontent.com/23257480/39624093-9d0a728c-4fca-11e8-9e0a-e8bb33088407.png)
不管是自己写的还是运行已有的代码，都会报这样的错误，求解答

**Comment by lewis617** [comment]
貌似是没有打包好，你先确定一下几件事：
1，安装了最新的 node；
2，使用 npm 或 yarn 安装依赖，不要使用 cnpm；
3，确定执行了书上的所有命令

**Comment by 812913** [comment]
重新下载安装了windows(x64) 8.11.1LTS，但是还是报同样的错误

**Comment by lewis617** [comment]
@812913  刚测试一下，无法复现你的错误，你确定按照书上的提示执行了正确的命令？
```
// 安装依赖
yarn

// 启动
npm start
```

**Comment by 812913** [comment]
@lewis617  我重新安装了依赖，这次可以了，非常感谢！
