### ISSUE TITLE
23章示例跑不起来

### ISSUE THREAD

**Issue by tabooc** [lewis617/react-redux-book#2]
运行 `npm install` 一切正常
`npm start` 后提示 `[webpack-isomorphic-tools] [error] asset not found: ./src/containers/Main/Main.scss`

node:v6.3.1
OS:windows 7 64

随后用`cnpm install`也是正常的,提示 `All packages installed...`
`npm start`后问题依旧

详细提示如下:

```
[webpack-isomorphic-tools] [error] asset not found: ./src/components/Spin/Spin.scss
Hash: 7b971385020909e6641b
Version: webpack 1.13.3
Time: 24660ms
                                  Asset     Size  Chunks             Chunk Names
89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]
f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]
448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]
af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]
fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]
fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]
e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]
674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]
912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]
b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]
           main-7b971385020909e6641b.js  9.34 MB       0  [emitted]  main
webpack built 7b971385020909e6641b in 24660ms
[webpack-isomorphic-tools] [error] asset not found: ./src/containers/Main/Main.scss
[webpack-isomorphic-tools] [error] asset not found: ./src/components/Spin/Spin.scss

```

**Comment by lewis617** [comment]
我刚才在 Mac、Windows7 和 Linux 上又测试了一遍，没有发现这个问题，你能给我一些其他的细节吗？比如，你的操作系统、Node版本、是否使用yarn或cnpm等。

**Comment by lewis617** [comment]
我仍然无法复现你的问题，或许你可以尝试这么做：

将node升级到6.9.1及以上。
将源指向淘宝。
将sass_binary_site指向淘宝的镜像。
使用yarn，别使用cnpm。
先尝试运行这本书的第三篇中的几章的示例代码。

**Comment by ttaccp** [comment]
我也是23章跑不起来

`npm install` 正常
`npm start`  出问题了

node 6.9.4
window10 64

使用cnpm也出问题


`npm install`
`All packages installed`


`npm start`
` ./~/.npminstall/css-loader/0.25.0/css-loader!./~/.npminstall/resolve-url-loader/1.6.1/resolve-url-loader!./~/.npminstall/sass-loader/3.2.3/sass-loader?sourceMap!./~/.npminstall/bootstrap-loader/1.3.3/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"useCustomIconFontPath":false,"extractStyles":false,"styleLoaders":["style","css","sass"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"c:/Users/ttaccp/Desktop/production/~/.npminstall/bootstrap-loader/1.3.3/bootstrap-loader/.bootstraprc-3-default","bootstrapPath":"c:/Users/ttaccp/Desktop/production/~/.npminstall/~/bootstrap-sass","bootstrapRelPath":"../~/bootstrap-sass"}!./~/.npminstall/bootstrap-loader/1.3.3/bootstrap-loader/no-op.js
[0] Module build failed:
[0] module.exports = {};`

**Comment by lewis617** [comment]
@ttaccp 
1，别用cnpm，国外有些开发者的轮子写得不规范，跟cnpm不兼容。使用配置了淘宝源的yarn（极力推荐）或npm。

如何加快yarn下载安装速度？使用yrm

```
npm i yrm -g
yrm use taobao
```
2，设置SASS_BINARY_SITE为https://npm.taobao.org/mirrors/node-sass/ ，设置fse_binary_host_mirror 为https://npm.taobao.org/mirrors/fsevents/ 

```
//windows
set SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/
set fse_binary_host_mirror=https://npm.taobao.org/mirrors/fsevents/ 

//linux or mac
export SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/
export fse_binary_host_mirror= https://npm.taobao.org/mirrors/fsevents/ 
```
然后再安装npm依赖包，其实一切都是“墙”的问题，如果你完全按照国外的模式在安装npm运行程序，没有任何问题。

**Comment by ttaccp** [comment]
感谢，已成功运行。

**Comment by tabooc** [comment]
我是全程用代理搞定的。。
有段时间没上了，没及时回复，抱歉。。

**Comment by Hlstack** [comment]
使用cnpm没问题，必须**全局安装**node-gyp
```bash
$ sudo cnpm install -g node-gyp
$ npm start  
```
