### ISSUE TITLE
redux store 结构问题

### ISSUE THREAD

**Issue by flicker85** [lewis617/react-redux-book#5]
请问，一个单页应用，有Link1, Link2, Link3，点不同链接，加载不同view，
请问redux store应该怎么设计呢？
root
  |---View1
  |---View2
  |---View3
如果store是上面的结构，Router变化，由View1切换到View2，是不是要把store View1节点下面的数据都清空？
如果不清空，那由View2再切换回View1时，上次查询和操作的状态数据就会被直接显示出来了。
或者是我redux store状态树设计的不对？

**Comment by lewis617** [comment]
state的设计很自由，有个澳洲前端来360做分享，说他就是以路由为分割，就是你写的那样。

路由跳转，view可以清空也可以不清空，清空可以当作重置功能，不清空可以作为缓存，减少http请求。所以你可以根据业务需求来！

**Comment by flicker85** [comment]
好的，那请问如果清空的话，应该在什么时候清空呢？
React Router里有OnEnter和onLeave，
比如View1切换View2，我在View1的onLeave里清空，可是清空后会先从新渲染View1为初始状态，然后才会跳转到View2。
感觉在OnEnter和onLeave里清空都不是很好，有没有比较好的清空redux状态树节点的时机呢？
我想达到的效果是：在离开View1时候把View1在redux状态树中的节点数据恢复为初始状态，但是不想让它从新渲染View1，而是直接切换到View2，进入View2的生命周期，这个应该怎么实现呢？

**Comment by lewis617** [comment]
方法很多很灵活，我是在OnEnter做的，你可以根据业务场景选择适合自己的。

**Comment by flicker85** [comment]
好的，谢谢~
